### ISSUE TITLE
小火箭下 YouTube 移动端应用翻译有问题

### ISSUE THREAD

**Issue by yang05051** [DualSubs/YouTube#15]
1. BoxJS 开启合成器模式之后，移动端应用默认打开视频后不显示原字幕；有概率出现字幕在开头几秒堆叠的情况（时间码有问题）
2. 移动端应用的翻译菜单在最近劫持失效了，不提供翻译选项的视频无法选择其他语言，所以无法修改翻译语言
3. YouTube Music 歌词翻译在最近失效

网页版没有任何问题，只有移动端应用有问题

系统版本是 iPadOS 17.4 正式版，小火箭版本是 2.2.45

**Comment by yang05051** [comment]
字幕堆叠的样例，只在合成器模式下出现，翻译器模式没问题

![IMG_3955](https://github.com/DualSubs/YouTube/assets/31024419/1cc4ea1b-254d-463d-806f-96cb54e52188)

**Comment by VirgilClyne** [comment]
https://youtu.be/HYCX4AjPXOA
