### ISSUE TITLE
YouTube music翻译挂掉好久了

### ISSUE THREAD

**Issue by 1017737237** [DualSubs/YouTube#18]
主要想问YouTube留言区自动翻译可以实现吗？薯条大神最近都在忙啥？

**Comment by 1017737237** [comment]
哎 我忘记说是啥工具了 是surge 上挂了好久啦 loon刚试了可以 虽然我都没用YouTube music 主要推荐薯条mm我目前在用的一个app：灵动歌词  最近mac版本也要出了 明天晚上我能拿到内测版本尝鲜 歌词app界的文班亚马 吊打musixmath这傻x 几块钱就能永久买断全平台更新 haha 我主要想问的问题这个app可以利用ios18的本地翻译模型 任何语言的歌词都能离线翻译 简直逆天 薯条mm可以把这个功能加到插件里吗。

**Comment by 1017737237** [comment]
@VirgilClyne 🥹

**Comment by VirgilClyne** [comment]
https://github.com/DualSubs/YouTube/releases/tag/v1.5.2
