### ISSUE TITLE
不太懂，为什么官网这样抽象？

### ISSUE THREAD

**Issue by lizyChy0329** [DualSubs/YouTube#21]
在 https://dualsubs.github.io/index.html 这个网站中，我只能看懂 “快速开始” 按钮，其他内容一概抓虾，无法理解，也不知怎样能够使用，是我有问题还是他有问题？

**Comment by xream** [comment]
你有问题

**Comment by Ftrybe** [comment]
官网的问题！它设计的不合理！它就应该进去什么都不用看，不用点我们就会用了！知识就不能主动进我们的脑子吗🐶

**Comment by lizyChy0329** [comment]
> 官网的问题！它设计的不合理！它就应该进去什么都不用看，不用点我们就会用了！知识就不能主动进我们的脑子吗🐶

不太理解一个应用的首页要公布如此多的技术细节，而且用户压根毫不关心
